trigger:
- master

jobs:
  - job: A
    container: ubuntu:16.04
    steps:
    - script: echo "A"

  - job: B
    container: debian:stretch
    steps:
    - script: echo "B"

  - job: C
    pool:
      vmImage: 'win1803'
    container: mcr.microsoft.com/windows/servercore:1803
    steps:
    - script: echo "Dependent C"
    dependsOn:
    - A
    - B