trigger:
- master

strategy:
  matrix:
    jdk10_linux:
      jdk_version: "1.10"
    jdk11_windows:
      jdk_version: "1.11"
  maxParallel: 2

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu:16.04

jobs:
  - job: A
    steps:
    - bash: echo "A"

  - job: B
    steps:
    - bash: echo "B"